env:
  name: "ALE/MarioBros-v5"
  frameskip: 4
  num_envs: 64
  num_actions: 18

training:
  total_steps: 1250000
  buffer_size: 1000000
  batch_size: 1024
  target_update_freq: 500
  eval_freq: 10000
  discount_rate: 0.99
  learning_rate: 1e-4
  life_loss_penalty: -1.0
  reward_scale: 800.0 # for Mario Bros, 800 points per enemy defeated

epsilon:
  max: 0.9
  min: 0.01
  exploration_frac: 0.2

eval:
  save_video: true
  video_fps: 30

eval_full:
  num_envs: 4
  grid_cols: 2
  video_fps: 30

paths:
  checkpoint_dir: "checkpoints"
  video_dir: "videos"
